package com.openosrs.api.widgets;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Varbits
{
	/*
	 * Kharedst's Memoirs Teleport Item
	 */
	KHAREDSTS_MEMOIRS_CHARGES(6035),

	/**
	 * Grand Exchange
	 */
	GRAND_EXCHANGE_PRICE_PER_ITEM(4398),


	/**
	 * Locked Prayers
	 * 0-7 = Locked
	 * 8 = Unlocked
	 */
	CHIVPIETY_UNLOCKED(3909),

	/**
	 * Locked Prayers
	 * 0 = Locked
	 * 1 = Unlocked
	 */

	RIGOUR_UNLOCKED(5451),
	AUGURY_UNLOCKED(5452),
	PRESERVE_UNLOCKED(5453),

	/**
	 * Theatre of Blood 1=In Party, 2=Inside/Spectator, 3=Dead Spectating
	 */
	THEATRE_OF_BLOOD(6440),
	BLOAT_DOOR(6447),

	/**
	 * Theatre of Blood orb varbits each number stands for the player's health on a scale of 1-27 (I think), 0 hides the orb
	 */
	THEATRE_OF_BLOOD_ORB_1(6442),
	THEATRE_OF_BLOOD_ORB_2(6443),
	THEATRE_OF_BLOOD_ORB_3(6444),
	THEATRE_OF_BLOOD_ORB_4(6445),
	THEATRE_OF_BLOOD_ORB_5(6446),

	/**
	 * Nightmare Zone
	 */
	NMZ_ABSORPTION(3956),
	NMZ_POINTS(3949),
	NMZ_OVERLOAD(3955),

	/**
	 * Pyramid plunder
	 */
	PYRAMID_PLUNDER_SARCO_OPEN(2362),
	PYRAMID_PLUNDER_CHEST_OPEN(2363),
	PYRAMID_PLUNDER_ROOM_LOCATION(2365),
	PYRAMID_PLUNDER_TIMER(2375),
	PYRAMID_PLUNDER_THIEVING_LEVEL(2376),
	PYRAMID_PLUNDER_ROOM(2377),

	/**
	 * In the Wilderness
	 */
	IN_THE_WILDERNESS(5963),

	/**
	 * Kingdom Management
	 */
	KINGDOM_FAVOR(72),
	KINGDOM_COFFER(74),
	KINGDOM_WORKERS_WOOD(81),
	KINGDOM_WORKERS_HERBS(82),
	KINGDOM_WORKERS_FISHING(83),
	KINGDOM_WORKERS_MINING(84),
	KINGDOM_WORKERS_FISH_COOKED_BUTTON(135), // 0 - Raw, 1 - Cooked
	KINGDOM_WORKERS_HARDWOOD(2131),
	KINGDOM_WORKERS_FARM(2132),
	KINGDOM_WORKERS_HARDWOOD_BUTTON(2133), // 0 - Mahogany, 1 - Teak, 2 - Both
	KINGDOM_WORKERS_HERBS_BUTTON(2134), // 0 - Herbs, 1 - Flax

	/**
	 * Varbit used for Slayer reward points
	 */
	SLAYER_REWARD_POINTS(4068),

	/**
	 * 0 = standard
	 * 1 = ancients
	 * 2 = lunars
	 * 3 = arrceus
	 **/
	SPELLBOOK(4070),

	/**
	 * Bank settings/flags
	 **/
	BANK_NOTE_FLAG(3958),


	/**
	 * Spells being auto-casted
	 */
	AUTO_CAST_SPELL(276),

	/**
	 * Temple Trekking
	 */
	TREK_POINTS(1955),
	TREK_STARTED(1956),
	TREK_EVENT(1958),
	TREK_STATUS(6719),
	BLOAT_ENTERED_ROOM(6447),

	/**
	 * f2p Quest varbits, these don't hold the completion value.
	 */
	QUEST_DEMON_SLAYER(2561),
	QUEST_GOBLIN_DIPLOMACY(2378),
	QUEST_MISTHALIN_MYSTERY(3468),
	QUEST_THE_CORSAIR_CURSE(6071),
	QUEST_X_MARKS_THE_SPOT(8063),
	QUEST_ERNEST_LEVER_A(1788),
	QUEST_ERNEST_LEVER_B(1789),
	QUEST_ERNEST_LEVER_C(1790),
	QUEST_ERNEST_LEVER_D(1791),
	QUEST_ERNEST_LEVER_E(1792),
	QUEST_ERNEST_LEVER_F(1793),

	/**
	 * member Quest varbits, these don't hold the completion value.
	 */
	QUEST_ANIMAL_MAGNETISM(3185),
	QUEST_BETWEEN_A_ROCK(299),
	QUEST_CONTACT(3274),
	QUEST_ZOGRE_FLESH_EATERS(487),
	QUEST_DARKNESS_OF_HALLOWVALE(2573),
	QUEST_DEATH_TO_THE_DORGESHUUN(2258),
	QUEST_DESERT_TREASURE(358),
	QUEST_DEVIOUS_MINDS(1465),
	QUEST_EAGLES_PEAK(2780),
	QUEST_ELEMENTAL_WORKSHOP_II(2639),
	QUEST_ENAKHRAS_LAMENT(1560),
	QUEST_ENLIGHTENED_JOURNEY(2866),
	QUEST_THE_EYES_OF_GLOUPHRIE(2497),
	QUEST_FAIRYTALE_I_GROWING_PAINS(1803),
	QUEST_FAIRYTALE_II_CURE_A_QUEEN(2326),
	QUEST_THE_FEUD(334), // 14 = able to pickpocket
	QUEST_FORGETTABLE_TALE(822),
	QUEST_GARDEN_OF_TRANQUILLITY(961),
	QUEST_GHOSTS_AHOY(217),
	QUEST_THE_GIANT_DWARF(571),
	QUEST_THE_GOLEM(346),
	QUEST_HORROR_FROM_THE_DEEP(34),
	QUEST_ICTHLARINS_LITTLE_HELPER(418),
	QUEST_IN_AID_OF_THE_MYREQUE(1990),
	QUEST_THE_LOST_TRIBE(532),
	QUEST_LUNAR_DIPLOMACY(2448),
	QUEST_MAKING_HISTORY(1383),
	QUEST_MOUNTAIN_DAUGHTER(260),
	QUEST_MOURNINGS_END_PART_II(1103),
	QUEST_MY_ARMS_BIG_ADVENTURE(2790),
	QUEST_RATCATCHERS(1404),
	QUEST_RECIPE_FOR_DISASTER(1850),
	QUEST_RECRUITMENT_DRIVE(657),
	QUEST_ROYAL_TROUBLE(2140),
	QUEST_THE_SLUG_MENACE(2610),
	QUEST_SHADOW_OF_THE_STORM(1372),
	QUEST_A_SOULS_BANE(2011),
	QUEST_SPIRITS_OF_THE_ELID(1444),
	QUEST_SWAN_SONG(2098),
	QUEST_A_TAIL_OF_TWO_CATS(1028),
	QUEST_TEARS_OF_GUTHIX(451),
	QUEST_WANTED(1051),
	QUEST_COLD_WAR(3293),
	QUEST_THE_FREMENNIK_ISLES(3311),
	QUEST_TOWER_OF_LIFE(3337),
	QUEST_WHAT_LIES_BELOW(3523),
	QUEST_OLAFS_QUEST(3534),
	QUEST_ANOTHER_SLICE_OF_HAM(3550),
	QUEST_DREAM_MENTOR(3618),
	QUEST_GRIM_TALES(2783),
	QUEST_KINGS_RANSOM(3888),
	QUEST_MONKEY_MADNESS_II(5027),
	QUEST_CLIENT_OF_KOUREND(5619),
	QUEST_BONE_VOYAGE(5795),
	QUEST_THE_QUEEN_OF_THIEVES(6037),
	QUEST_THE_DEPTHS_OF_DESPAIR(6027),
	QUEST_DRAGON_SLAYER_II(6104),
	QUEST_TALE_OF_THE_RIGHTEOUS(6358),
	QUEST_A_TASTE_OF_HOPE(6396),
	QUEST_MAKING_FRIENDS_WITH_MY_ARM(6528),
	QUEST_THE_ASCENT_OF_ARCEUUS(7856),
	QUEST_THE_FORSAKEN_TOWER(7796),
	//TODO
	QUEST_SONG_OF_THE_ELVES(7796),

	/**
	 * mini-quest varbits, these don't hold the completion value.
	 */
	QUEST_ARCHITECTURAL_ALLIANCE(4982),
	QUEST_BEAR_YOUR_SOUL(5078),
	QUEST_CURSE_OF_THE_EMPTY_LORD(821),
	QUEST_ENCHANTED_KEY(1391),
	QUEST_THE_GENERALS_SHADOW(3330),
	QUEST_SKIPPY_AND_THE_MOGRES(1344),
	QUEST_LAIR_OF_TARN_RAZORLOR(3290),
	QUEST_FAMILY_PEST(5347),
	QUEST_THE_MAGE_ARENA_II(6067),
	//TODO
	QUEST_IN_SEARCH_OF_KNOWLEDGE(6067),

	/**
	 * Spellbook filtering (1 = unfiltered, 0 = filtered)
	 */
	FILTER_SPELLBOOK(6718),

	/**
	 * POH Building mode (1 = yes, 0 = no)
	 */
	BUILDING_MODE(2176),

	/**
	 * 1 if in game, 0 if not
	 */
	LMS_IN_GAME(5314),

	/**
	 * Amount of pvp kills in current game
	 */
	LMS_KILLS(5315),

	/**
	 * The x coordinate of the final safespace (world coord)
	 */
	LMS_SAFE_X(5316),

	LMS_POISON_PROGRESS(5317),

	/**
	 * The y coordinate of the final safespace (world coord)
	 */
	LMS_SAFE_Y(5320),

	/**
	 * 1 is true, 0 is false.
	 */
	GAUNTLET_FINAL_ROOM_ENTERED(9177),

	/**
	 * 1 is true, 0 is false.
	 */
	GAUNTLET_ENTERED(9178),

	WITHDRAW_X_AMOUNT(3960),

	IN_PVP_AREA(8121),

	/**
	 * Value of hotkey varbits can be 0-13
	 * 0 corresponds to no hotkey set
	 * 1-12 correspond to F1-F12 respectively
	 * 13 corresponds to escape
	 */
	COMBAT_TAB_HOTKEY(4675),
	STATS_TAB_HOTKEY(4676),
	QUESTS_TAB_HOTKEY(4677),
	INVENTORY_TAB_HOTKEY(4678),
	EQUIPMENT_TAB_HOTKEY(4679),
	PRAYER_TAB_HOTKEY(4680),
	SPELLBOOK_TAB_HOTKEY(4682),
	FRIENDS_TAB_HOTKEY(4684),
	ACCOUNT_MANAGEMENT_TAB_HOTKEY(6517),
	LOGOUT_TAB_HOTKEY(4689),
	OPTIONS_TAB_HOTKEY(4686),
	EMOTES_TAB_HOTKEY(4687),
	CLAN_TAB_HOTKEY(4683),
	MUSIC_TAB_HOTKEY(4688),

	/**
	 * Chat Notifications settings
	 * <br>
	 * LOOT_DROP_NOTIFICATIONS: 1 is true, 0 is false
	 * LOOT_DROP_NOTIFICATIONS_VALUE: gp value
	 * UNTRADEABLE_LOOT_NOTIFICATIONS: 1 is true, 0 is false
	 * BOSS_KILL_COUNT_UPDATES: 1 is filtered, 0 is unfiltered
	 * DROP_ITEM_WARNINGS: 1 is true, 0 is false
	 * DROP_ITEM_WARNINGS_VALUE: gp value
	 */
	LOOT_DROP_NOTIFICATIONS(5399),
	LOOT_DROP_NOTIFICATIONS_VALUE(5400),
	UNTRADEABLE_LOOT_NOTIFICATIONS(5402),
	BOSS_KILL_COUNT_UPDATES(4930),
	DROP_ITEM_WARNINGS(5411),
	DROP_ITEM_WARNINGS_VALUE(5412),

	PARASITE(10151),
	;

	/**
	 * The raw varbit ID.
	 */
	private final int id;
}
