package net.runelite.client.plugins.theatre;

public enum SlayerTasks
{
    ABERRANT_SPECTRES("Aberrant spectres"),
    ABYSSAL_DEMONS("Abyssal demons"),
    ANKOUS("Ankous"),
    BANSHEES("Banshees"),
    BASILISKS("Basilisks"),
    BATS("Bats"),
    BEARS("Bears"),
    BIRDS("Birds"),
    BLACK_DEMONS("Black demons"),
    BLACK_DRAGONS("Black dragons"),
    BLOODVELDS("Bloodvelds"),
    BLUE_DRAGONS("Blue dragons"),
    BRINE_RATS("Brine rats"),
    BRONZE_DRAGONS("Bronze dragons"),
    CATABLEPON("Catablepon"),
    CAVE_BUGS("Cave bugs"),
    CAVE_CRAWLERS("Cave crawlers"),
    CAVE_HORRORS("Cave horrors"),
    CAVE_SLIMES("Cave slimes"),
    COCKATRICES("Cockatrices"),
    COWS("Cows"),
    CRAWLING_HANDS("Crawling Hands"),
    CROCODILES("Crocodiles"),
    DAGANNOTHS("Dagannoths"),
    DARK_BEASTS("Dark beasts"),
    DOGS("Dogs"),
    DUST_DEVILS("Dust devils"),
    DWARFS("Dwarfs"),
    EARTH_WARRIORS("Earth Warriors"),
    ELVES("Elves"),
    FEVER_SPIDERS("Fever spiders"),
    FIRE_GIANTS("Fire giants"),
    FLESH_CRAWLERS("Flesh Crawlers"),
    FOSSIL_ISLAND_WYVERNS("Fossil Island wyverns"),
    GARGOYLES("Gargoyles"),
    GHOSTS("Ghosts"),
    GHOULS("Ghouls"),
    GOBLINS("Goblins"),
    GORAKS("Goraks"),
    GREATER_DEMONS("Greater demons"),
    GREEN_DRAGONS("Green dragons"),
    HARPIE_BUG_SWARMS("Harpie bug swarms"),
    HELLHOUNDS("Hellhounds"),
    HILL_GIANT("Hill Giant"),
    HOBGOBLINS("Hobgoblins"),
    HYDRAS("Hydras"),
    ICEFIENDS("Icefiends"),
    ICE_GIANTS("Ice giants"),
    ICE_WARRIORS("Ice warriors"),
    INFERNAL_MAGES("Infernal Mages"),
    IRON_DRAGONS("Iron dragons"),
    JELLIES("Jellies"),
    JUNGLE_HORRORS("Jungle horrors"),
    LIZARDMEN("Lizardmen"),
    LIZARDS("Lizards"),
    KALPHITES("Kalphites"),
    KILLERWATTS("Killerwatts"),
    KURASKS("Kurasks"),
    LESSER_DEMONS("Lesser demons"),
    MITHRIL_DRAGONS("Mithril dragons"),
    MINOTAURS("Minotaurs"),
    MOGRES("Mogres"),
    MOLANISKS("Molanisks"),
    MONKEYS("Monkeys"),
    MOSS_GIANTS("Moss giants"),
    NECHRYAELS("Nechryaels"),
    OGRES("Ogres"),
    OTHERWORLDLY_BEINGS("Otherworldly beings"),
    PYREFIENDS("Pyrefiends"),
    RED_DRAGONS("Red dragons"),
    ROCKSLUGS("Rockslugs"),
    SCABARITES("Scabarites"),
    SCORPIONS("Scorpions"),
    SEA_SNAKES("Sea snakes"),
    SHADES("Shades"),
    SHADOW_WARRIORS("Shadow warriors"),
    SKELETAL_WYVERNS("Skeletal Wyverns"),
    SKELETONS("Skeletons"),
    SMOKE_DEVILS("Smoke devils"),
    SPIDERS("Spiders"),
    STEEL_DRAGONS("Steel dragons"),
    SUQAHS("Suqahs"),
    TERROR_DOGS("Terror dogs"),
    TROLLS("Trolls"),
    TUROTHS("Turoths"),
    VAMPYRES("Vampyres"),
    WALL_BEASTS("Wall beasts"),
    WATERFIENDS("Waterfiends"),
    WEREWOLVES("Werewolves"),
    WOLVES("Wolves"),
    ZOMBIES("Zombies"),
    ZYGOMITES("Zygomites");

    private String name;

    SlayerTasks(String name)
    {
        this.name = name;
    }

    public String getName()
    {
        return name;
    }
}
