name: Auto Sync Fork

on:
  schedule:
  - cron: '*/30 * * * *'

jobs:
  sync:

    runs-on: ubuntu-latest
    
    steps:
    - uses: TG908/fork-sync@v1.1.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        owner: open-osrs
        base: master
        head: master
        merge_method: merge
        pr_message: automatic merge from upstream
        
