name: RunelitePlus - Auto approve

on: pull_request

jobs:
  approve:

    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'github-actions[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"