name: OpenOSRS - Scraper

on:
  schedule:
    - cron: "0 0 * * 2,5"

jobs:
  scrape-npcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Assembling cache client
        run: ./gradlew :cache-client:assemble --console=plain
      - name: Assembling scraper
        run: ./gradlew :wiki-scraper:assemble --console=plain
      - name: Building cache client
        run: ./gradlew :cache-client:build --console=plain
      - name: Building scraper
        run: ./gradlew :wiki-scraper:build --console=plain
      - name: Downloading jagex cache
        run: ./gradlew :cache-client:update --console=plain
      - name: Scraping NPC stats
        run: ./gradlew :wiki-scraper:npcStatsScrape --console=plain
      - name: Create NPC stats Pull Request
        uses: peter-evans/create-pull-request@master
        env:
          GITHUB_TOKEN: ${{ secrets.OpenOSRS }}
          PULL_REQUEST_BRANCH: NPC-UPDATE
          PULL_REQUEST_TITLE: 'Client: Update NPC stats'
          PULL_REQUEST_BODY: This is an auto-generated PR with changes from the OSRS wiki
          COMMIT_MESSAGE: 'Client: Update NPC stats'

  scrape-items:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Assembling cache client
        run: ./gradlew :cache-client:assemble --console=plain
      - name: Assembling scraper
        run: ./gradlew :wiki-scraper:assemble --console=plain
      - name: Building cache client
        run: ./gradlew :cache-client:build --console=plain
      - name: Building scraper
        run: ./gradlew :wiki-scraper:build --console=plain
      - name: Downloading jagex cache
        run: ./gradlew :cache-client:update --console=plain
      - name: Scraping item stats
        run: ./gradlew :wiki-scraper:npcStatsScrape --console=plain
      - name: Create item stats Pull Request
        uses: peter-evans/create-pull-request@master
        env:
          GITHUB_TOKEN: ${{ secrets.OpenOSRS }}
          PULL_REQUEST_BRANCH: ITEM-STATS-UPDATE
          PULL_REQUEST_TITLE: 'Client: Update item stats'
          PULL_REQUEST_BODY: This is an auto-generated PR with changes from the OSRS wiki
          COMMIT_MESSAGE: 'Client: Update item stats'