name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: test

    steps:
      - uses: actions/checkout@v1
      - name: checkout submods
        run: git submodule update --init --recursive
